### ISSUE TITLE
follow up todo

### ISSUE THREAD

**Issue by Plep-m** [Plep-m/AnubisOS#3]
in order to adress the previous issue i figured out that before implementing keyboard driver i need plenty of other things like an IDT 

- [ ] Define a global descriptor table (GDT)

- [ ] Let the CPU know where the GDT lives

- [ ] Define an interrupt descriptor table (IDT)

- [ ] Let the CPU know where the IDT lives

- [ ] Provide interrupt handler code for CPU interrupts
